import type { Metadata } from "next";
import { Gorditas } from "next/font/google";
import "./globals.css";
import  Navbar  from "@/layout-ui/Navbar";

const gordita = Gorditas({
  subsets: ['latin'],
  weight: ['400', '700'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={gordita.className}>
       <main>
        <Navbar/>
       {children}
       </main>
        </body>
    </html>
  );
}
